# Generated by Django 2.1.7 on 2019-02-24 06:32

from django.db import migrations

def populate_data(apps, schema_editor):
    Bank = apps.get_model('cryptoserver', 'Bank')
    Bank(username='usbank1', password='usbank123', name='us bank', money=50000000, public_key='').save()
    Bank(username='midwestbank1', password='midwest123', name='MidWestBank', money=10000000, public_key='').save()

    Trader = apps.get_model('cryptoserver', 'Trader')
    Trader(username='ben1', password='ben123', name='Ben', money=0).save()
    Trader(username='phillip1', password='phillip123', name='Phillip', money=10).save()

    Company = apps.get_model('cryptoserver', 'Company')
    Company(username='hyperledger1', password='hyper123', name='HyperLedger', money=150000).save()
    Company(username='jpmorgan1', password='jp123', name='JPMorgan', money=12550000).save()


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoserver', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
